### ISSUE TITLE
cb is not a function

### ISSUE THREAD

**Issue by dgrim1214** [parmentf/hubot-ector#7]
Despite following the installation instructions for hubot and hubot-ector, I have been unable to make it work. Upon launching hubot, I receive these two errors:

```
Error while loading cn.json
Error: ENOENT: no such file or directory, open 'cn.json'
```

Then, during operation of the bot, any string not caught by other hubot scripts will return

```
ERROR TypeError: cb is not a function
  at [object Object].ConceptNetwork.addNode (/home/xxxx/domibot/node_modules/concept-network/lib/concept-network.js:66:5)
  at Object.Ector.addEntry (/home/xxxx/domibot/node_modules/hubot-ector/node_modules/ector/lib/ector.js:134:30)
  at /home/xxxx/domibot/node_modules/hubot-ector/src/ector.coffee:58:7, <js>:51:15
  at Listener.callback (/home/xxxx/domibot/node_modules/hubot/src/robot.coffee:236:52, <js>:162:16)
  at executeListener (/home/xxxx/domibot/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/home/xxxx/domibot/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /home/xxxx/domibot/node_modules/hubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/home/xxxx/domibot/node_modules/hubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/home/xxxx/domibot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
  at /home/xxxx/domibot/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by parmentf** [comment]
Oh, yes. This is due to bug in node-ector's dependencies. See parmentf/node-ector#4
When I'll have the energy, I'll fix the dependency.
In the interval, you can always modify the `package.json` of the `node-ector` node_module, by removing the `^` character on the `concept-network` line...
Then go to the directory of `node-ector`, and run `npm install`.

Sorry for the inconvenience.
